{% set name = "covseisnet" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d1056e57eac833bb576008b990cb04fc8a9d953e0ef996eba06f53647429895

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - obspy
    - python
    - scipy

test:
  imports:
    - covseisnet
  requires:
    - pip
  commands:
    - pip check
    - python -c "import covseisnet"

about:
  home: https://covseisnet.gricad-pages.univ-grenoble-alpes.fr/covseisnet
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: Covariance matrix analysis of network seismic data
  description: |
    The `covseisnet` package provides tools for array signal processing, with a focus on data from seismic networks. The central analyzed mathematical construction is the array covariance matrix (sometimes called network covariance matrix). The core signal detection algorithms are based on the analysis of the eigenvalues of this matrix. Eigenvector decomposition provides a basis for a blind source separation. In addition, the covariance matrix can be used as input for classical array processing tools such as beamforming and inter-station cross-correlations. Covseisnet objects are mostly inherited from obspy (seismology-oriented python package) and `numpy`.
  doc_url: https://covseisnet.gricad-pages.univ-grenoble-alpes.fr/covseisnet
  dev_url: https://github.com/covseisnet/covseisnet

extra:
  recipe-maintainers:
    - FrancisTong
